CFLAGS:append = " -pipe -funsigned-char -DFNFLOAT -DCK_NEWTERM -DPOSIX -UNOUNICODE"
CFLAGS:append = " -UNOPUSH -UNOHELP -UNOFRILLS -UNOPUSH -DNO_OPENPTY"
CFLAGS:append = " -UNOB_115K -UNOSERVER -UNODEBUG -DDEBUG"
CFLAGS:append = " -DTCPSOCKET -DNOLISTEN -DNOLOGIN"

CFLAGS:append = " -UNOCSETS -UNONET -UNOFTP -UNODIAL -UNOPUSH -UNOIKSD -UNOHTTP -UDNOFLOAT"
CFLAGS:append = " -UNOSEXP -UNORLOGIN -UNOOLDMODEMS -UNOSSH -UNOLISTEN -UNORESEND -UNOAUTODL"
CFLAGS:append = " -UNOSTREAMING -UNOHINTS -UNOCKXYZ -UNOLEARN -UNOMKDIR -UNOPERMS -UNOCKTIMERS"
CFLAGS:append = " -UNOCKREGEX -UNOLOGDIAL -DNOLOCAL -DZLIB"
