#!/bin/sh
PSPLASH_PID=`pidof psplash-drm`
if [[ ! -z $PSPLASH_PID ]]; then
    echo -n "Stop psplash: "
    echo QUIT > /tmp/splash_fifo
    echo "done."
    PSPLASH_PID=`pidof psplash-drm`
    if [[ ! -z $PSPLASH_PID ]]; then
        kill -9 $PSPLASH_PID
    fi
fi
/bin/true
